
import NavBar from '@/components/NavBar/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

// Next-Auth Session Provider
import { getServerSession } from 'next-auth'
import SessionProvider from '@/components/SessionProvider/SessionProvider'
import { authOptions } from "@/app/api/auth/[...nextauth]/authProviders";

export const metadata = {
  title: 'Next GYM',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
      <SessionProvider>
        <NavBar></NavBar>
        {children}
        <Footer></Footer>
        </SessionProvider>
        </body>
    </html>
  )
}
